# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:8181/")
    self.driver.set_window_size(1202, 821)
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("admin")
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.ID, "txtPassword").send_keys("P")
    self.driver.find_element(By.ID, "txtPassword").send_keys("P@$$w0rd")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-in-alt").click()
    assert self.driver.find_element(By.ID, "userData").text == "Hola Administrador"
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
  
